version: "3.8"
services:
    app:
        #build:
        #    context: ./
        image: "ghcr.io/developkosarev/frontolservicenext:latest"
        ports:
            - "3000:3000"    
        working_dir: /opt/app
        container_name: frontol_next_nodejs