name: Publish Docker image
env:
  DEPLOY_PACKAGE_NAME : "frontol-service-next-${{ github.sha }}"
  DEPLOY_VERSION : "v0.0.3"
  DEPLOY_FOLDER : "docker"

#on:
#  release:
#    types: [published]

on:
  workflow_dispatch: {}
  push:
    branches: [master]
    tags:
        - 'v*'

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: 01. Check out the repo
        uses: actions/checkout@v4
            
      - name: 02. Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 03. Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}

      - name: 04. Execute few commands
        run : |
          echo "Deploy package name: ${{ env.DEPLOY_PACKAGE_NAME }}"
          echo "Deploy version: ${{ env.DEPLOY_VERSION }}"
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          echo "Labels: ${{ steps.meta.outputs.labels }}"

      - name: 05. Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  #deploy-frontol:
  #  name: Deploy
  #  needs: push_to_registries
  #  runs-on: ubuntu-latest
  #
  #  steps:
  #    - name: 01. Execure few commands
  #      run: |
  #        echo "Deploy application"
  #        echo "Appication name: ${{ env.DEPLOY_PACKAGE_NAME }}"
  #
  #    - name: 02. Install SSH Key
  #      uses: shimataro/ssh-key-action@v2
  #      with:
  #        key: ${{ secrets.SSH_PRIVATE_KEY }}
  #        known_hosts: ${{ secrets.SSH_HOST_V2 }}
  #
  #    - name: 03. Adding Known Hosts
  #      run: ssh-keyscan -H ${{ secrets.SSH_HOST_V2 }} >> ~/.ssh/known_hosts
  #
  #    - name: 04. Restart container
  #      run: |
  #        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_V2 }} \
  #        "cd /home/${{ secrets.SSH_USER }}/${{ env.DEPLOY_FOLDER }} \
  #        && docker compose -f compose-frontol.yml pull \
  #        && docker compose -f compose-frontol.yml down \
  #        && docker compose -f compose-frontol.yml up -d"
  #