name: Ping hosts
env:
  DEPLOY_PACKAGE_NAME : "frontol-service-next-${{ github.sha }}"
  DEPLOY_VERSION : "v0.0.1"
  DEPLOY_FOLDER : "docker"

on:
  workflow_dispatch: {}
  push:
    branches: [add-action-ping]

jobs:
  deploy-frontol:
    name: Ping
    runs-on: ubuntu-latest

    steps:
      - name: 01. Execute few commands
        run: |
          echo "Deploy application"
          echo "Appication name: ${{ env.DEPLOY_PACKAGE_NAME }}"

      - name: 02. Ping google
        run: ping google.com -c4

      - name: 03. Ping google
        run: ping ipv6.google.com -c4

      - name: 04. Ping host
        run: ping ${{ secrets.SSH_HOST_V2 }} -c4
